//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankMember()
        {
            this.RequestWithdraws = new HashSet<RequestWithdraw>();
        }
    
        public int ID { get; set; }
        public int BankID { get; set; }
        public int MemberID { get; set; }
        public string Account { get; set; }
        public string AccountOwner { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CrteatedDate { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestWithdraw> RequestWithdraws { get; set; }
    }
}
