//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigTransportCost
    {
        public int ID { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public double FirstDistance { get; set; }
        public int FirstPrice { get; set; }
        public int PerKmPrice { get; set; }
        public Nullable<double> FirstWeight { get; set; }
        public Nullable<double> PerKg { get; set; }
        public Nullable<int> PerKgPrice { get; set; }
        public Nullable<int> FeeCOD { get; set; }
        public Nullable<int> BonusFee { get; set; }
        public Nullable<int> FistKgPrice { get; set; }
        public int Type { get; set; }
        public Nullable<int> TransportType { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual VehicleType VehicleType { get; set; }
    }
}
