//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigTransportWeight
    {
        public int ID { get; set; }
        public double Weight { get; set; }
        public int Price { get; set; }
        public int TransportAreaID { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ConfigTransportArea ConfigTransportArea { get; set; }
    }
}
