//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.BankMembers = new HashSet<BankMember>();
            this.MembersTransactionHistories = new HashSet<MembersTransactionHistory>();
            this.Notifications = new HashSet<Notification>();
            this.Wallets = new HashSet<Wallet>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ShiperID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string User { get; set; }
        public string Password { get; set; }
        public string DeviceID { get; set; }
        public string Token { get; set; }
        public string ConfirmCode { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsLogin { get; set; }
        public System.DateTime ExpriceDateOTP { get; set; }
        public int Status { get; set; }
        public int QtyOTP { get; set; }
        public System.DateTime OTPDateTime { get; set; }
        public string Lang { get; set; }
        public Nullable<int> ShopID { get; set; }
        public string KeyChat { get; set; }
        public string RoomID { get; set; }
        public string OldPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankMember> BankMembers { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Shiper Shiper { get; set; }
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MembersTransactionHistory> MembersTransactionHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wallet> Wallets { get; set; }
    }
}
