//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WE_SHIPEntities : DbContext
    {
        public WE_SHIPEntities()
            : base("name=WE_SHIPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppVersion> AppVersions { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<BankMember> BankMembers { get; set; }
        public virtual DbSet<CarShiper> CarShipers { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<CategoryNew> CategoryNews { get; set; }
        public virtual DbSet<ComplainOrder> ComplainOrders { get; set; }
        public virtual DbSet<Config> Configs { get; set; }
        public virtual DbSet<ConfigCommission> ConfigCommissions { get; set; }
        public virtual DbSet<ConfigTime> ConfigTimes { get; set; }
        public virtual DbSet<ConfigTransportArea> ConfigTransportAreas { get; set; }
        public virtual DbSet<ConfigTransportCost> ConfigTransportCosts { get; set; }
        public virtual DbSet<ConfigTransportWeight> ConfigTransportWeights { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<CouponCustomer> CouponCustomers { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerLocation> CustomerLocations { get; set; }
        public virtual DbSet<CustomerRank> CustomerRanks { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<HistoryRankingPoint> HistoryRankingPoints { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MembersTransactionHistory> MembersTransactionHistories { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<OrderService> OrderServices { get; set; }
        public virtual DbSet<OrderServiceDetail> OrderServiceDetails { get; set; }
        public virtual DbSet<OrderServiceImage> OrderServiceImages { get; set; }
        public virtual DbSet<OrderServiceStatusHistory> OrderServiceStatusHistories { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<Promotion> Promotions { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<QA> QAs { get; set; }
        public virtual DbSet<RequestWithdraw> RequestWithdraws { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceImage> ServiceImages { get; set; }
        public virtual DbSet<ServicePrice> ServicePrices { get; set; }
        public virtual DbSet<Shiper> Shipers { get; set; }
        public virtual DbSet<ShiperArea> ShiperAreas { get; set; }
        public virtual DbSet<ShiperImage> ShiperImages { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<ShopImage> ShopImages { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Toping> Topings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VehicleType> VehicleTypes { get; set; }
        public virtual DbSet<Wallet> Wallets { get; set; }
    }
}
