//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public News()
        {
            this.Promotions = new HashSet<Promotion>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string UrlImage { get; set; }
        public int OrderDisplay { get; set; }
        public int Status { get; set; }
        public int Type { get; set; }
        public int TypeSend { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int UserID { get; set; }
        public bool IsShowCreate { get; set; }
        public int isAdvertusement { get; set; }
        public string Link { get; set; }
    
        public virtual CategoryNew CategoryNew { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promotion> Promotions { get; set; }
    }
}
