//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderServiceStatusHistory
    {
        public int ID { get; set; }
        public int OrderServiceID { get; set; }
        public int Status { get; set; }
    
        public virtual OrderService OrderService { get; set; }
    }
}
