//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderServiceDetail
    {
        public int ID { get; set; }
        public int OrderServiceID { get; set; }
        public int ServicePriceID { get; set; }
        public int Price { get; set; }
        public int BasePrice { get; set; }
        public int Quantity { get; set; }
        public string Toping { get; set; }
        public string Note { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual OrderService OrderService { get; set; }
        public virtual ServicePrice ServicePrice { get; set; }
    }
}
