//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestWithdraw
    {
        public int ID { get; set; }
        public int ShiperID { get; set; }
        public int BankMemberID { get; set; }
        public string Account { get; set; }
        public int Amount { get; set; }
        public string Owner { get; set; }
        public int Status { get; set; }
        public System.DateTime CreaedDate { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public int IsActive { get; set; }
    
        public virtual BankMember BankMember { get; set; }
        public virtual Shiper Shiper { get; set; }
    }
}
