//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shiper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Shiper()
        {
            this.CarShipers = new HashSet<CarShiper>();
            this.Members = new HashSet<Member>();
            this.OrderServices = new HashSet<OrderService>();
            this.RequestWithdraws = new HashSet<RequestWithdraw>();
            this.ShiperAreas = new HashSet<ShiperArea>();
            this.ShiperImages = new HashSet<ShiperImage>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string AvartarUrl { get; set; }
        public double Rating { get; set; }
        public bool IsAcceptService { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public int IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public double RatingAdmin { get; set; }
        public int CommissionID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public double Longi { get; set; }
        public double Lati { get; set; }
        public int IsInternal { get; set; }
        public string Identification { get; set; }
        public Nullable<long> WithDrawSum { get; set; }
        public int Sex { get; set; }
        public Nullable<int> IsVip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarShiper> CarShipers { get; set; }
        public virtual ConfigCommission ConfigCommission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Member> Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderService> OrderServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestWithdraw> RequestWithdraws { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiperArea> ShiperAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShiperImage> ShiperImages { get; set; }
    }
}
